### ISSUE TITLE
How to train custom version of trigram_hashmap.ser file ?

### ISSUE THREAD

**Issue by textproofreading** [brybailey/NLPWordPredictor#5]
hi all,

How to train custom version of trigram_hashmap.ser file ?

the code is great for reading to explain how to predict words , I want to training my custom version .

could you share code about this ?

thanks

**Comment by brybailey** [comment]
Hi textproofreading,

To train your own custom version, you can either (a) serialize your own data set before program initialization or you can (b) update the n-gram probabilities after each session with the user, which will require a HashMap buffer and a reserializing of data after each use, which will be fairly resource intensive. 

(a) You'll need to have your custom training set in a .txt file and use a StringTokenizer to read the probabilities and grams into the HashMap. After it is full, you can serialize it into a file to be read by the program with:

`try { ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(new File("trigram_hashmap.ser")));
                    oos.writeObject( trigrams ); // This is your data set HashMap
                    oos.close();
                } catch( IOException e ) {
                    System.err.println( "Failed to Serialize file" );
                    System.err.println( e.getStackTrace() );
                }`

(b) The process is the same, except you will need to parse each n-gram set as it is being typed into the GUI window and store it in a buffer HashMap to serialize periodically and save user training data

Hope this helps!
